export const userSelect = {
  id: true,
  first_name: true,
  last_name: true,
  email: true,
  phone_number: true,
  profile_pic: true,
  role: true,
  is_anonymous: true,
  is_verified: true,
  is_deleted: true,
  is_email_verified: true,
  is_phone_number_verified: true,
  saveForLater: true,
  notification: true,
  user_settings: true,
  created_at: true,
  updated_at: true,
}
